Repository wecode-bootcamp-korea/40-2nd-Abnb-backend, pull requests merged in 2023-01, with the labels that each got.

#3 [40기 이가은] ADD: 상세페이지 기능 구현 완료
  app.js
  controllers/productController.js
  controllers/userController.js
  db/migrations/20221226120411_products_table.sql
  models/productDao.js
  models/userDao.js
  routers/index.js
  routers/productRouter.js
  routers/userRouter.js
  services/productService.js
  services/userService.js
  test/user.test.js
Labels: 멘토 리뷰 요청

#5 [40기 이정우] Feature/bookings 기능 구현 완료
  controllers/productController.js
  middlewares/validation.js
  models/productDao.js
  models/userDao.js
  routers/index.js
  routers/productRouter.js
  services/productService.js
Labels: Conflict 해결 요청

#4 [40기 이정우] ADD: main-page GET 기능구현 완료
  controllers/productController.js
  models/productDao.js
  routers/index.js
  routers/productRouter.js
  services/productService.js
  test/products.test.js
  util/queryBuilder.js
Labels: 완료
